{{/*
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
*/}}

################################
## Airflow API Server Service
#################################
{{- if and .Values.apiServer.enabled (semverCompare ">=3.0.0" .Values.airflowVersion) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-api-server
  labels:
    tier: airflow
    component: api-server
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- if or (.Values.labels) (.Values.apiServer.labels) }}
      {{- mustMerge .Values.apiServer.labels .Values.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.apiServer.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiServer.service.type }}
  selector:
    tier: airflow
    component: api-server
    release: {{ .Release.Name }}
  ports:
  {{ range .Values.apiServer.service.ports }}
    -
      {{- range $key, $val := . }}
      {{ $key }}: {{ tpl (toString $val) $ }}
      {{- end }}
  {{- end }}
  {{- if .Values.apiServer.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.apiServer.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.apiServer.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.apiServer.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
{{- end }}
