# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---

name: Airflow E2E Tests

permissions:
  contents: read
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      workflow-name:
        description: "Name of the test"
        type: string
        required: true
      runners:
        description: "The array of labels (in json form) determining runners."
        type: string
        default: '["ubuntu-24.04"]'
      platform:
        description: "Platform for the build - 'linux/amd64' or 'linux/arm64'"
        type: string
        default: 'linux/amd64'
      default-python-version:
        description: "Which version of python should be used by default"
        type: string
        default: '3.10'
      use-uv:
        description: "Whether to use uv to build the image (true/false)"
        type: string
        default: 'true'
      docker-image-tag:
        description: "Tag of the Docker image to test"
        type: string
        required: true
      e2e_test_mode:
        description: "Test mode - basic or remote_log"
        type: string
        default: "basic"

  workflow_call:
    inputs:
      workflow-name:
        description: "Name of the test"
        type: string
        required: true
      runners:
        description: "The array of labels (in json form) determining runners."
        required: true
        type: string
      platform:
        description: "Platform for the build - 'linux/amd64' or 'linux/arm64'"
        required: true
        type: string
      default-python-version:
        description: "Which version of python should be used by default"
        required: true
        type: string
      use-uv:
        description: "Whether to use uv to build the image (true/false)"
        required: true
        type: string
      docker-image-tag:
        description: "Tag of the Docker image to test"
        type: string
        default: ""
      e2e_test_mode:
        description: "Test mode - quick or full"
        type: string
        default: "basic"

jobs:
  test-e2e-integration-tests:
    timeout-minutes: 60
    name: ${{ inputs.workflow-name }}
    runs-on: ${{ fromJSON(inputs.runners) }}
    env:
      PYTHON_MAJOR_MINOR_VERSION: "${{ inputs.default-python-version }}"
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USERNAME: ${{ github.actor }}
      VERBOSE: "true"
    steps:
      - name: "Cleanup repo"
        shell: bash
        run: docker run -v "${GITHUB_WORKSPACE}:/workspace" -u 0:0 bash -c "rm -rf /workspace/*"
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: "Prepare breeze & PROD image: ${{ env.PYTHON_MAJOR_MINOR_VERSION }}"
        uses: ./.github/actions/prepare_breeze_and_image
        with:
          platform: ${{ inputs.platform }}
          image-type: "prod"
          python: ${{ env.PYTHON_MAJOR_MINOR_VERSION }}
          use-uv: ${{ inputs.use-uv }}
          make-mnt-writeable-and-cleanup: true
        id: breeze
      - name: "Test e2e integration tests"
        run: breeze testing airflow-e2e-tests
        env:
          DOCKER_IMAGE: "${{ inputs.docker-image-tag }}"
          E2E_TEST_MODE: "${{ inputs.e2e_test_mode }}"
      - name: Zip logs
        run: |
          cd ./airflow-e2e-tests && zip -r logs.zip logs
        if: always()
      - name: "Upload logs"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: "e2e-test-logs-${{ inputs.e2e_test_mode }}"
          path: './airflow-e2e-tests/logs.zip'
          retention-days: '7'
          if-no-files-found: 'error'
        if: always()
